# Generated by Django 5.2.1 on 2025-06-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.TextField(max_length=100)),
                ('course_id', models.IntegerField()),
                ('course_video', models.URLField()),
            ],
            options={
                'db_table': 'course_details',
            },
        ),
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.TextField()),
                ('s_id', models.IntegerField()),
                ('s_email', models.EmailField(max_length=254)),
                ('s_password', models.IntegerField()),
                ('s_qualification', models.TextField()),
                ('status', models.TextField(default='pending')),
                ('course', models.ManyToManyField(to='elearnapp.course_details')),
            ],
            options={
                'db_table': 'student_details',
            },
        ),
    ]
