# Generated by Django 5.2.1 on 2025-06-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearnapp', '0002_student_details_otp_student_details_otp_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='id',
        ),
        migrations.AlterField(
            model_name='student_details',
            name='s_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
