# Generated by Django 5.2.1 on 2025-06-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearnapp', '0003_remove_student_details_id_alter_student_details_s_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_details',
            name='id',
        ),
        migrations.AlterField(
            model_name='course_details',
            name='course_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='course',
            field=models.ManyToManyField(related_name='students', to='elearnapp.course_details'),
        ),
    ]
