# Generated by Django 5.2.1 on 2025-06-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearnapp', '0004_remove_course_details_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_details',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='student_details',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='course_details',
            name='course_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='course',
            field=models.ManyToManyField(to='elearnapp.course_details'),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='s_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='s_password',
            field=models.IntegerField(unique=True),
        ),
    ]
